name: CI

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Linux Kernel Version'
        required: true
      build_debian_version:
        description: 'Build Debian Version'
        required: true
      makeflags:
        required: false
      ssh:
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - uses: actions/checkout@v4
      - name: Change docker data folder
        run: |
          echo '{
              "data-root": "'$GITHUB_WORKSPACE/docker'"
          }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create artifact folder
        run: mkdir artifact
      - name: build docker image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            KERNEL_VERSION=${{ github.event.inputs.kernel_version }}
            BUILD_DEBIAN_VERSION=${{ github.event.inputs.build_debian_version }}
            MAKEFLAGS_ADD=${{ github.event.inputs.makeflags }}
          load: true
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kernel_build_image
          target: download_kernel
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Start SSH via tmate
        if: github.event.inputs.ssh == 'true'
        uses: P3TERX/ssh2actions@main
      - name: Check disk free space
        run: df -h
      - name: build docker image
        if: github.event.inputs.ssh != 'true'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            KERNEL_VERSION=${{ github.event.inputs.kernel_version }}
            BUILD_DEBIAN_VERSION=${{ github.event.inputs.build_debian_version }}
            MAKEFLAGS_ADD=${{ github.event.inputs.makeflags }}
          load: true
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kernel_build_image
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Check disk free space
        if: always()
        run: df -h
      - name: retrieve artifact from docker image
        if: github.event.inputs.ssh != 'true'
        run: |
          docker run -it --name kernel_build -d kernel_build_image:latest
      - name: Start SSH via tmate
        if: github.event.inputs.ssh != 'true' && always()
        uses: P3TERX/ssh2actions@main
      - uses: actions/upload-artifact@v4
        with:
            path: artifact/
